padding: "calc(var(--nav-height, 70px) + 20px) 20px 20px",
  boxSizing: "border-box",
  },
container: {
  maxWidth: "900px",
    margin: "0 auto",
      padding: "20px",
  },
backButton: {
  background: "linear-gradient(135deg, #ffc947, #ff8c42)",
    color: "#1a0f0a",
      border: "none",
        padding: "10px 20px",
          borderRadius: "8px",
            fontSize: "16px",
              fontWeight: "600",
                cursor: "pointer",
                  marginBottom: "20px",
  },
title: {
  fontSize: "2.5rem",
    fontWeight: "700",
      color: "#ffc947",
        marginBottom: "20px",
          textAlign: "center",
            fontFamily: "'Playfair Display', serif",
  },
imageWrapper: {
  width: "100%",
    maxWidth: "600px",
      margin: "0 auto 20px",
        borderRadius: "12px",
          overflow: "hidden",
            boxShadow: "0 8px 24px rgba(0, 0, 0, 0.3)",
  },
image: {
  width: "100%",
    height: "auto",
      maxHeight: "400px",
        objectFit: "cover",
          display: "block",
  },
details: {
  background: "rgba(45, 24, 16, 0.5)",
    padding: "20px",
      borderRadius: "12px",
        border: "1px solid rgba(255, 140, 66, 0.2)",
          marginBottom: "20px",
  },
description: {
  fontSize: "16px",
    lineHeight: "1.8",
      color: "#f5e6d3",
        marginBottom: "16px",
  },
info: {
  fontSize: "15px",
    color: "#ff8c42",
      marginBottom: "8px",
  },
message: {
  padding: "12px 16px",
    background: "rgba(255, 201, 71, 0.2)",
      border: "1px solid #ffc947",
        borderRadius: "8px",
          color: "#ffc947",
            fontWeight: "600",
              textAlign: "center",
                marginBottom: "20px",
  },
button: {
  width: "100%",
    maxWidth: "300px",
      display: "block",
        margin: "0 auto",
          padding: "12px 20px",
            fontSize: "16px",
              fontWeight: "700",
                color: "#1a0f0a",
                  background: "linear-gradient(135deg, #ffc947, #ff8c42)",
                    border: "none",
                      borderRadius: "12px",
                        boxShadow: "0 4px 12px rgba(255, 140, 66, 0.4)",
                          transition: "all 0.3s ease",
  },
};

export default CourseDetails;